### ISSUE TITLE
环信仿微信的项目 你down 下来跑过吗

### ISSUE THREAD

**Issue by 13120241790** [CameloeAnthony/Perfect_IM_SNS#1]
环信仿微信的项目 你down 下来跑过吗，垃圾得不行 切换 tab 都卡得不行 还 crash。实在是垃圾中的战斗机 这样还能骗 1K+ 的 star 。真没业界良心啊 很多功能都是虚的 还不如 凡信（也是仿微信的基于环信的项目）。

**Comment by ProgrammerAnthony** [comment]
之前看了下源码 。聊天这一块集成功能还比较全。代码写的比较简单。对初学者还是很有帮助的 。至于放在第一位推荐的原因，也是因为star数比其他开源项目多得多吧 。                 后面我会再看一下的。

**Comment by lubobill1990** [comment]
这是环信广告？
